name: wifey-prod

services:
  frontend:
    container_name: wifey-prod-frontend
    build:
      context: ./wifey-app-frontend
      target: build
      args:
        BUILD_MODE: prod
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: wifey-prod-backend
    build: ./wifey-app-backend
    ports:
      - "3000:3000"
    volumes:
      - ./wifey-app-backend:/app
      - /app/node_modules
      - sqlite_data_prod:/app/data
    environment:
      - NODE_ENV=production
    env_file:
      - ./wifey-app-backend/.env
    restart: unless-stopped

volumes:
  sqlite_data_prod:
